table _Mahmoud
	lineageTag: 8d7c7134-3f40-4e57-81e5-19f25b820a6c

	measure 'Avg. Grade' = AVERAGE(FactStudentPerformance[Student_Grade])*10
		formatString: 0.00
		lineageTag: d9d7b15e-c6bb-414d-a156-d2f437091c86

	measure 'Total Active Students' = ```
			DISTINCTCOUNT(FactStudentPerformance[StudentKey])
			
			```
		formatString: 0.0
		lineageTag: 586e05b4-56b3-4901-9cf0-ad6fa0f70ce5

	measure 'Students Passing Exam' =
			
			VAR StudentExamGrades =
			    SUMMARIZE(
			        FactStudentPerformance,
			        FactStudentPerformance[StudentKey],
			        FactStudentPerformance[ExamKey],
			        "ExamGrade", SUM(FactStudentPerformance[Student_Grade])
			    )
			RETURN
			    COUNTROWS(
			        FILTER(
			            StudentExamGrades,
			            [ExamGrade] >=6
			        )
			    )
		formatString: 0
		lineageTag: be3f6af5-b504-49fe-bbaf-734af4c6bf39

	measure Failure = countrows(FactStudentFailure)
		formatString: 0
		lineageTag: d9ecc246-484b-4c23-83ff-0220f0fe057c

	measure 'Students Passing Exam1' =
			
			VAR StudentExamGrades =
			    SUMMARIZE(
			        FactStudentPerformance,
			        FactStudentPerformance[StudentKey],
			        FactStudentPerformance[ExamKey],
			        "TotalGrade", SUM(FactStudentPerformance[Student_Grade])
			    )
			VAR PassingStudents =
			    FILTER(
			        StudentExamGrades,
			        [TotalGrade] >= 6
			    )
			RETURN
			    COUNTROWS(
			        SUMMARIZE(
			            PassingStudents,
			            [StudentKey]  // Group by StudentKey only to get unique students
			        )
			    )
		formatString: 0
		lineageTag: 2a57e05b-6201-43a2-ad07-13ca33ce1871

	measure 'Total Students per Instructor' =
			
			CALCULATE(
			    DISTINCTCOUNT(FactStudentPerformance[StudentKey]),
			    USERELATIONSHIP(DimInstructor[InstructorKey], FactStudentPerformance[InstructorKey])
			)
		formatString: 0
		lineageTag: 5d9accfc-a1a2-4a37-9d14-4969dc411a6e

	measure 'Avg. Course Grade' =
			
			CALCULATE(
			    AVERAGE(FactStudentPerformance[Student_Grade]),
			    ALLEXCEPT(DimCourse, DimCourse[CourseKey])
			)
		lineageTag: 546ea337-e0b6-4594-be6c-b4ff0bdcb73f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hardest Course1' =
			
			VAR CourseGrades =
			    SUMMARIZE(
			        DimCourse,
			        DimCourse[Course_Name],
			        "AvgGrade", [Avg. Course Grade]
			    )
			VAR MinGrade = MINX(CourseGrades, [AvgGrade])
			RETURN
			    MAXX(
			        FILTER(CourseGrades, [AvgGrade] = MinGrade),
			        DimCourse[Course_Name]
			    )
		lineageTag: 1747152d-1055-4f36-8599-7c258b25d1a1

	measure 'Total Distinct Exams' =
			
			DISTINCTCOUNT(FactStudentPerformance[ExamKey])
		formatString: 0
		lineageTag: a4947d85-bca3-4330-a2a6-ad8e264e154f

	measure 'Overall Failure Rate' =
			
			DIVIDE(
			    [Failure],
			    [Total Students],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 35309638-cfe8-4d5e-99f1-b44c1604f713

	measure 'Track Failure Rate' = ```
			
			VAR StudentsInTrack = 
			    CALCULATE(
			        COUNTROWS(DimStudent),
			        ALLEXCEPT(DimTrack, DimTrack[Track_Name])
			    )
			VAR FailuresInTrack = 
			    CALCULATE(
			        [Failure],
			        ALLEXCEPT(DimTrack, DimTrack[Track_Name])
			    )
			RETURN
			DIVIDE(FailuresInTrack, StudentsInTrack, 0)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ada080ed-dabb-4e5b-bbac-b6c9eb25c7a5

	measure 'Avg Performance of Failed Students' = ```
			
			CALCULATE(
			    AVERAGE(FactStudentPerformance[Student_Grade]),
			    DimStudent[Student_ITI_Status] = "Failed to Graduate"
			)
			
			
			
			```
		lineageTag: 62937361-dbba-4539-a490-2d78e5d18f57

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Performance of Graduated Students' = ```
			
			CALCULATE(
			    AVERAGE(FactStudentPerformance[Student_Grade]),
			    DimStudent[Student_ITI_Status] = "Graduated"
			)
			
			
			```
		lineageTag: 2ac4126d-2b31-4237-9ef9-3b5ed0afe499

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Performance Gap' = ```
			
			[Avg Performance of Graduated Students] - [Avg Performance of Failed Students]
			
			```
		lineageTag: 5b55fccf-fa79-4118-ad46-b5a56d996579

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Is High Risk Track' = ```
			
			IF([Overall Failure Rate]> 0.10, "⚠️ High Risk", "✓ Normal")
			
			```
		lineageTag: d91e661a-1ee0-45f3-88e9-cb82b5ad4dc0

	measure 'Total Tracks' = DISTINCTCOUNT(DimTrack[TrackKey])
		formatString: 0
		lineageTag: 887d9d3a-d36a-442e-bc3a-f93d0c1f51a3

	column Column
		formatString: 0
		lineageTag: d6fbd1cd-cb24-445c-b463-c743d36d5720
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Mahmoud = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 3d90e9b8bcbb4620806cd9afe819fa99

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

