table _Mahmoud
	lineageTag: 8d7c7134-3f40-4e57-81e5-19f25b820a6c

	measure 'Avg. Grade' = AVERAGE(FactStudentPerformance[Student_Grade])*10
		formatString: 0.00
		lineageTag: d9d7b15e-c6bb-414d-a156-d2f437091c86

	measure 'Total Active Students' = ```
			DISTINCTCOUNT(FactStudentPerformance[StudentKey])
			
			```
		formatString: 0.0
		lineageTag: 586e05b4-56b3-4901-9cf0-ad6fa0f70ce5

	measure 'Students Passing Exam' =
			
			VAR StudentExamGrades =
			    SUMMARIZE(
			        FactStudentPerformance,
			        FactStudentPerformance[StudentKey],
			        FactStudentPerformance[ExamKey],
			        "ExamGrade", SUM(FactStudentPerformance[Student_Grade])
			    )
			RETURN
			    COUNTROWS(
			        FILTER(
			            StudentExamGrades,
			            [ExamGrade] >=6
			        )
			    )
		formatString: 0
		lineageTag: be3f6af5-b504-49fe-bbaf-734af4c6bf39

	measure Failure = countrows(FactStudentFailure)
		formatString: 0
		lineageTag: d9ecc246-484b-4c23-83ff-0220f0fe057c

	measure 'Students Passing Exam1' =
			
			VAR StudentExamGrades =
			    SUMMARIZE(
			        FactStudentPerformance,
			        FactStudentPerformance[StudentKey],
			        FactStudentPerformance[ExamKey],
			        "TotalGrade", SUM(FactStudentPerformance[Student_Grade])
			    )
			VAR PassingStudents =
			    FILTER(
			        StudentExamGrades,
			        [TotalGrade] >= 6
			    )
			RETURN
			    COUNTROWS(
			        SUMMARIZE(
			            PassingStudents,
			            [StudentKey]  // Group by StudentKey only to get unique students
			        )
			    )
		formatString: 0
		lineageTag: 2a57e05b-6201-43a2-ad07-13ca33ce1871

	measure 'Total Students per Instructor' =
			
			CALCULATE(
			    DISTINCTCOUNT(FactStudentPerformance[StudentKey]),
			    USERELATIONSHIP(DimInstructor[InstructorKey], FactStudentPerformance[InstructorKey])
			)
		formatString: 0
		lineageTag: 5d9accfc-a1a2-4a37-9d14-4969dc411a6e

	column Column
		formatString: 0
		lineageTag: d6fbd1cd-cb24-445c-b463-c743d36d5720
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Mahmoud = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 3d90e9b8bcbb4620806cd9afe819fa99

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

