table DimCompany
	lineageTag: 2f9140b2-d625-4165-b326-4ab14d17130a

	column CompanyKey
		dataType: int64
		formatString: 0
		lineageTag: fb4716af-f483-467e-9c81-482755099077
		summarizeBy: none
		sourceColumn: CompanyKey

		annotation SummarizationSetBy = Automatic

	column Company_ID
		dataType: int64
		formatString: 0
		lineageTag: bd31bbcf-b9ac-4a65-a49a-b47ea8e52c27
		summarizeBy: none
		sourceColumn: Company_ID

		annotation SummarizationSetBy = Automatic

	column Company_Name
		dataType: string
		lineageTag: b96e1265-1288-4d15-bfde-9854910441ca
		summarizeBy: none
		sourceColumn: Company_Name

		annotation SummarizationSetBy = Automatic

	column Company_Location
		dataType: string
		lineageTag: 2529eeb5-21e0-4bc0-b719-c9d61e865d22
		summarizeBy: none
		sourceColumn: Company_Location

		annotation SummarizationSetBy = Automatic

	column Company_Type
		dataType: string
		lineageTag: 2afb7411-3aad-4dc9-a8ff-a309e4eabe83
		summarizeBy: none
		sourceColumn: Company_Type

		annotation SummarizationSetBy = Automatic

	column Field
		dataType: string
		lineageTag: aa1ebc73-9cc1-449a-beda-6f08c900353c
		summarizeBy: none
		sourceColumn: Field

		annotation SummarizationSetBy = Automatic

	partition DimCompany = m
		mode: import
		source =
				let
				    Source = Sql.Databases("."),
				    ITI_DW = Source{[Name="ITI_DW"]}[Data],
				    dbo_DimCompany = ITI_DW{[Schema="dbo",Item="DimCompany"]}[Data],
				    #"Merged Queries" = Table.NestedJoin(dbo_DimCompany, {"CompanyKey"}, #"Companies Fileds", {"CompanKey"}, "Companies Fileds", JoinKind.LeftOuter),
				    #"Expanded Companies Fileds" = Table.ExpandTableColumn(#"Merged Queries", "Companies Fileds", {"Field"}, {"Field"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded Companies Fileds",{"CompanyKey", "Company_ID", "Company_Name", "Company_Location", "Company_Type", "Field", "FactStudentOutcomes"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Reordered Columns","Smart Village, Giza","Smart Village",Replacer.ReplaceText,{"Company_Location"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","6th of October, Giza","6th of October",Replacer.ReplaceText,{"Company_Location"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

