table DimCompany
	lineageTag: d305daa1-dff5-4ceb-9039-0b50348b1485

	column CompanyKey
		dataType: int64
		formatString: 0
		lineageTag: 621138b7-18d9-4344-9b7f-fb35576b62e8
		summarizeBy: none
		sourceColumn: CompanyKey

		annotation SummarizationSetBy = Automatic

	column Company_ID
		dataType: int64
		formatString: 0
		lineageTag: 56afadd4-4cee-4fb9-a25b-0726616f4f3b
		summarizeBy: none
		sourceColumn: Company_ID

		annotation SummarizationSetBy = Automatic

	column Company_Name
		dataType: string
		lineageTag: 49a7db31-a068-4789-9ec8-138d2b8a8f30
		summarizeBy: none
		sourceColumn: Company_Name

		annotation SummarizationSetBy = Automatic

	column Company_Location
		dataType: string
		lineageTag: ff600b11-49ca-409c-98cc-281fa795071b
		summarizeBy: none
		sourceColumn: Company_Location

		annotation SummarizationSetBy = Automatic

	column Company_Type
		dataType: string
		lineageTag: 6294af76-4742-4411-b3f1-a3e20f1d5580
		summarizeBy: none
		sourceColumn: Company_Type

		annotation SummarizationSetBy = Automatic

	column Field
		dataType: string
		lineageTag: 84646b4a-546b-49ff-afe4-42e5297d18b8
		summarizeBy: none
		sourceColumn: Field

		annotation SummarizationSetBy = Automatic

	partition DimCompany = m
		mode: import
		source =
				let
				    Source = Sql.Databases("."),
				    ITI_DW = Source{[Name="ITI_DW"]}[Data],
				    dbo_DimCompany = ITI_DW{[Schema="dbo",Item="DimCompany"]}[Data],
				    #"Merged Queries" = Table.NestedJoin(dbo_DimCompany, {"CompanyKey"}, #"Companies Fileds", {"CompanKey"}, "Companies Fileds", JoinKind.LeftOuter),
				    #"Expanded Companies Fileds" = Table.ExpandTableColumn(#"Merged Queries", "Companies Fileds", {"Field"}, {"Field"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded Companies Fileds","Smart Village, Giza","Smart Village",Replacer.ReplaceText,{"Company_Location"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","6th of October, Giza","6th of October",Replacer.ReplaceText,{"Company_Location"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

