table DimStudent
	lineageTag: ca816423-ba23-469a-b54e-0c84bc109538

	column StudentKey
		dataType: int64
		formatString: 0
		lineageTag: 99e2c9ef-12d8-4c27-84e6-74335676003e
		summarizeBy: none
		sourceColumn: StudentKey

		annotation SummarizationSetBy = Automatic

	column Student_ID
		dataType: int64
		formatString: 0
		lineageTag: 8a232c99-c50a-4798-9750-88263b764451
		summarizeBy: count
		sourceColumn: Student_ID

		annotation SummarizationSetBy = Automatic

	column Student_FullName
		dataType: string
		lineageTag: 649e2ec0-193c-40eb-b8d2-0931a341f1f7
		summarizeBy: none
		sourceColumn: Student_FullName

		annotation SummarizationSetBy = Automatic

	column Student_Gender
		dataType: string
		lineageTag: 706000cb-3a53-46f0-894f-e26fdb917c57
		summarizeBy: none
		sourceColumn: Student_Gender

		annotation SummarizationSetBy = Automatic

	column Student_Mail
		dataType: string
		lineageTag: 56175ea4-e698-4785-96f5-a83b758215e2
		summarizeBy: none
		sourceColumn: Student_Mail

		annotation SummarizationSetBy = Automatic

	column Student_Birthdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 95473c3e-f603-4745-b85e-f2777146d54b
		summarizeBy: none
		sourceColumn: Student_Birthdate

		variation Variation
			isDefault
			relationship: c97076b7-1d2c-45d3-b01c-254c6eb21330
			defaultHierarchy: LocalDateTable_872af1ea-694b-4fd6-a457-f5c393adf202.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Phone
		dataType: string
		lineageTag: cc3d4ff7-0f62-49b0-97aa-59ee9fdd182d
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column Student_Marital_Status
		dataType: string
		lineageTag: 8f0165ee-baef-4156-9c7f-d3da9788369a
		summarizeBy: none
		sourceColumn: Student_Marital_Status

		annotation SummarizationSetBy = Automatic

	column Student_Faculty
		dataType: string
		lineageTag: 9e6db8c6-7872-46d9-9edd-f0b0fac7699c
		summarizeBy: none
		sourceColumn: Student_Faculty

		annotation SummarizationSetBy = Automatic

	column Student_Faculty_Grade
		dataType: string
		lineageTag: 6818a168-fa64-4372-9f35-8cbfdf9ccd16
		summarizeBy: none
		sourceColumn: Student_Faculty_Grade

		annotation SummarizationSetBy = Automatic

	column Student_ITI_Status
		dataType: string
		lineageTag: 19c6d91d-41d2-4fee-847f-76832aa2359a
		summarizeBy: none
		sourceColumn: Student_ITI_Status

		annotation SummarizationSetBy = Automatic

	column TrackKey
		dataType: int64
		formatString: 0
		lineageTag: a5f8fb7f-413a-4e47-91fd-f75cefc89414
		summarizeBy: none
		sourceColumn: TrackKey

		annotation SummarizationSetBy = Automatic

	column BranchKey
		dataType: int64
		formatString: 0
		lineageTag: 85465ae2-01ec-49d1-8574-123692086091
		summarizeBy: none
		sourceColumn: BranchKey

		annotation SummarizationSetBy = Automatic

	column IntakeKey
		dataType: int64
		formatString: 0
		lineageTag: 4e7df60a-dfb7-433a-a7b9-1b5235864630
		summarizeBy: none
		sourceColumn: IntakeKey

		annotation SummarizationSetBy = Automatic

	column Social_Facebook
		dataType: string
		lineageTag: cc0ff4d0-6489-4cef-bf97-c65e15d5b377
		summarizeBy: none
		sourceColumn: Social_Facebook

		annotation SummarizationSetBy = Automatic

	column Social_LinkedIn
		dataType: string
		lineageTag: 4f4c4d58-7fbd-4fa5-81f5-cedb508597d0
		summarizeBy: none
		sourceColumn: Social_LinkedIn

		annotation SummarizationSetBy = Automatic

	column Social_GitHub
		dataType: string
		lineageTag: 937cbabf-9a4e-4f50-ba06-27ba01e4f92e
		summarizeBy: none
		sourceColumn: Social_GitHub

		annotation SummarizationSetBy = Automatic

	column Social_X
		dataType: string
		lineageTag: cbaa9d90-569f-453c-968f-2936fc79c370
		summarizeBy: none
		sourceColumn: Social_X

		annotation SummarizationSetBy = Automatic

	column Social_Instagram
		dataType: string
		lineageTag: a0f7c299-8c6c-4492-91f7-f6565a9dc622
		summarizeBy: none
		sourceColumn: Social_Instagram

		annotation SummarizationSetBy = Automatic

	column County
		dataType: string
		lineageTag: 45efe471-5c2d-4f67-9bfb-e54e1df888a8
		summarizeBy: none
		sourceColumn: County

		annotation SummarizationSetBy = Automatic

	partition DimStudent = m
		mode: import
		source =
				let
				    Source = Sql.Databases("."),
				    ITI_DW = Source{[Name="ITI_DW"]}[Data],
				    dbo_DimStudent = ITI_DW{[Schema="dbo",Item="DimStudent"]}[Data],
				    #"Split Column by Delimiter" = Table.SplitColumn(dbo_DimStudent, "Student_Address", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"Student_Address.1", "Student_Address.2"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Student_Address.1", type text}, {"Student_Address.2", type text}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "County", each if [Student_Address.2] = null then [Student_Address.1] else [Student_Address.2]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column",{"Student_Address.1", "Student_Address.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"County", type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type1",{{"County", Text.Trim, type text}})
				in
				    #"Trimmed Text"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

