table DimStudent
	lineageTag: c28fdf97-2dc6-4faa-b7b7-c24cb7613f81

	column StudentKey
		dataType: int64
		formatString: 0
		lineageTag: e2574d2d-081d-40b7-8f5b-2bcfb63ccefd
		summarizeBy: none
		sourceColumn: StudentKey

		annotation SummarizationSetBy = Automatic

	column Student_ID
		dataType: int64
		formatString: 0
		lineageTag: 14f56878-cdad-4289-ae8b-b64f5b6799a8
		summarizeBy: count
		sourceColumn: Student_ID

		annotation SummarizationSetBy = Automatic

	column Student_FullName
		dataType: string
		lineageTag: 3db7258a-8931-47b5-a630-9a675cb69221
		summarizeBy: none
		sourceColumn: Student_FullName

		annotation SummarizationSetBy = Automatic

	column Student_Gender
		dataType: string
		lineageTag: 2cc0280f-9d22-4020-9b06-26306dca58fb
		summarizeBy: none
		sourceColumn: Student_Gender

		annotation SummarizationSetBy = Automatic

	column Student_Mail
		dataType: string
		lineageTag: 3d411bc3-d4de-45ac-9f03-505976a0f8c8
		summarizeBy: none
		sourceColumn: Student_Mail

		annotation SummarizationSetBy = Automatic

	column Student_Birthdate
		dataType: dateTime
		formatString: Long Date
		lineageTag: ff4f0d69-a203-4e59-bc21-b7c21c7d7aa8
		summarizeBy: none
		sourceColumn: Student_Birthdate

		variation Variation
			isDefault
			relationship: db9514d4-d53e-4856-8892-f56fe1884548
			defaultHierarchy: LocalDateTable_798cbbd7-3e4a-4a16-b9e2-b70a1ffc0aa1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Phone
		dataType: string
		lineageTag: 35dcc432-7359-498f-9072-1ace543466cd
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column Student_Marital_Status
		dataType: string
		lineageTag: 45e36a30-ede2-4ede-90b3-874825581340
		summarizeBy: none
		sourceColumn: Student_Marital_Status

		annotation SummarizationSetBy = Automatic

	column Student_Faculty
		dataType: string
		lineageTag: f48129cd-73e8-4eb7-8888-ec39167fdf21
		summarizeBy: none
		sourceColumn: Student_Faculty

		annotation SummarizationSetBy = Automatic

	column Student_Faculty_Grade
		dataType: string
		lineageTag: f4939cbe-b580-4032-b499-3a8411f6fcb7
		summarizeBy: none
		sourceColumn: Student_Faculty_Grade

		annotation SummarizationSetBy = Automatic

	column Student_ITI_Status
		dataType: string
		lineageTag: b41fdeb2-d47b-4f48-98bb-37c680b5cad4
		summarizeBy: none
		sourceColumn: Student_ITI_Status

		annotation SummarizationSetBy = Automatic

	column TrackKey
		dataType: int64
		formatString: 0
		lineageTag: d95f0e06-72c2-4863-aba2-afe7c95759cb
		summarizeBy: none
		sourceColumn: TrackKey

		annotation SummarizationSetBy = Automatic

	column BranchKey
		dataType: int64
		formatString: 0
		lineageTag: 2cc1036d-7012-4fde-9a2d-33b8de25645f
		summarizeBy: none
		sourceColumn: BranchKey

		annotation SummarizationSetBy = Automatic

	column IntakeKey
		dataType: int64
		formatString: 0
		lineageTag: b29915d1-7db6-437b-974a-45186cb632f9
		summarizeBy: none
		sourceColumn: IntakeKey

		annotation SummarizationSetBy = Automatic

	column Social_Facebook
		dataType: string
		lineageTag: 88a410e8-29b0-4372-93a7-5508dff67a49
		summarizeBy: none
		sourceColumn: Social_Facebook

		annotation SummarizationSetBy = Automatic

	column Social_LinkedIn
		dataType: string
		lineageTag: 59ec5eb8-f57b-44c1-b90a-cbc2248ca026
		summarizeBy: none
		sourceColumn: Social_LinkedIn

		annotation SummarizationSetBy = Automatic

	column Social_GitHub
		dataType: string
		lineageTag: 6ab4ee99-6580-4ddd-b0cd-8c855369dc90
		summarizeBy: none
		sourceColumn: Social_GitHub

		annotation SummarizationSetBy = Automatic

	column Social_X
		dataType: string
		lineageTag: 2eaf6618-c978-4157-a3e4-1a33b156b365
		summarizeBy: none
		sourceColumn: Social_X

		annotation SummarizationSetBy = Automatic

	column Social_Instagram
		dataType: string
		lineageTag: 0a4ec387-0e4d-47e0-8705-a668f31df066
		summarizeBy: none
		sourceColumn: Social_Instagram

		annotation SummarizationSetBy = Automatic

	column 'Student_Address.1'
		dataType: string
		lineageTag: 45d1ca06-7442-45b8-8e95-0c583a4301b4
		summarizeBy: none
		sourceColumn: Student_Address.1

		annotation SummarizationSetBy = Automatic

	column 'Student_Address.2'
		dataType: string
		lineageTag: 1f9b8855-2a5b-4933-aa6c-5d13a61dd5f5
		summarizeBy: none
		sourceColumn: Student_Address.2

		annotation SummarizationSetBy = Automatic

	column County
		dataType: string
		lineageTag: 4a5d5c38-a229-4535-891f-16e9605567a3
		summarizeBy: none
		sourceColumn: County

		annotation SummarizationSetBy = Automatic

	partition DimStudent = m
		mode: import
		source =
				let
				    Source = Sql.Databases("."),
				    ITI_DW = Source{[Name="ITI_DW"]}[Data],
				    dbo_DimStudent = ITI_DW{[Schema="dbo",Item="DimStudent"]}[Data],
				    #"Split Column by Delimiter" = Table.SplitColumn(dbo_DimStudent, "Student_Address", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"Student_Address.1", "Student_Address.2"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Student_Address.1", type text}, {"Student_Address.2", type text}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "County", each if [Student_Address.2] = null then [Student_Address.1] else [Student_Address.2]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column",{{"County", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

