table FactSocial
	lineageTag: a14893c8-ee25-479c-8aaa-154749bb5324

	column name
		dataType: string
		lineageTag: e380f5a7-2d05-42b0-a34f-081f3e9acfdc
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: 30648f4a-4680-4ea7-82ee-2ce32d63791d
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column middle_name
		dataType: string
		lineageTag: 7c9ed3be-c873-443a-bd09-cd72b75ad3c6
		summarizeBy: none
		sourceColumn: middle_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: 47df0dab-8156-4014-9b7b-ca1a88cd666f
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column created_time
		dataType: dateTime
		formatString: General Date
		lineageTag: 159d180c-78ef-4818-b27b-2fc91dd0741e
		summarizeBy: none
		sourceColumn: created_time

		variation Variation
			isDefault
			relationship: 3ac60f02-872a-4eec-a729-63ac2dde20ef
			defaultHierarchy: LocalDateTable_e8a099f7-9140-4e3e-aa9a-4b7f0dd54d49.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column message
		dataType: string
		lineageTag: 0c3d8ca7-56ec-4097-b3c4-211852983ceb
		summarizeBy: none
		sourceColumn: message

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 71675e58-21ef-474d-b762-52dd4f7edae7
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: fa20ffa8-c198-4eaf-a093-b0848ee877b9
			defaultHierarchy: LocalDateTable_5733a8ca-9ff9-4ee6-8f9c-bf31ab0bc451.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: f1a0c40a-3b49-4c45-b646-7968221f4d34
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column CoptionsTypes = IF(ISBLANK(FactSocial[message])  ,"Empty Captions", "written Caption")
		lineageTag: 5c633353-e7b8-45a5-99e2-b6b53ee24f55
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column WeekDay = ```
			FORMAT(FactSocial[Date],"dddd") 
			```
		lineageTag: a90f43ed-2e89-47a1-b467-b046e2e81c59
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition FactSocial = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("https://graph.facebook.com/v24.0/me?fields=id,name,first_name,middle_name,last_name,posts.limit(1000)&access_token=EAA8b8Y8L2EYBP6k3MJMDjLY6gYsMhXFjHmdlx4KSVBuONR9QnMrq0ZCeVolIcAGilLWMQ6SEbCib3unb2xjcGhjh7HI1RxETkcZA5OHqB7CTWzSIfzrRHdnuZAHxLnQx3LoH5Uzw0rGfUwVLjEDVvWH6Hb0NAmZBCiRYwRdLFX1tdw8EyHpMQ0YHbUEt5HlA")),
				    #"Converted to Table" = Table.FromRecords({Source}),
				    #"Expanded posts" = Table.ExpandRecordColumn(#"Converted to Table", "posts", {"data", "paging"}, {"posts.data", "posts.paging"}),
				    #"Expanded posts.data" = Table.ExpandListColumn(#"Expanded posts", "posts.data"),
				    #"Expanded posts.data1" = Table.ExpandRecordColumn(#"Expanded posts.data", "posts.data", {"created_time", "id", "message"}, {"created_time", "id.1", "message"}),
				    #"Expanded posts.paging" = Table.ExpandRecordColumn(#"Expanded posts.data1", "posts.paging", {"previous", "next"}, {"posts.paging.previous", "posts.paging.next"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded posts.paging",{"id", "posts.paging.previous", "posts.paging.next"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"message", type text}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type",{"id.1"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns1",{{"created_time", type datetime}}),
				    #"Inserted Date" = Table.AddColumn(#"Changed Type1", "Date", each DateTime.Date([created_time]), type date),
				    #"Inserted Time" = Table.AddColumn(#"Inserted Date", "Time", each DateTime.Time([created_time]), type time)
				in
				    #"Inserted Time"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

