table HaithamMeasures
	lineageTag: 90789787-27ad-4b31-bd0f-411734b53e3d

	measure 'Total Rating Submitted' = COUNTROWS(FactStudentRating)
		formatString: 0.0
		lineageTag: 12419d00-1bc8-41ed-a260-da35e50b4e26

	measure '% Students Submitting Ratings' = DIVIDE(DISTINCTCOUNT(FactStudentRating[StudentKey]), DISTINCTCOUNT(DimStudent[StudentKey]))
		formatString: 0%;-0%;0%
		lineageTag: 2b3a2fc6-1f68-402f-8c48-5066390f297d

	measure 'Total Certificates Acquired' = COUNTROWS(FactCertificate)
		formatString: 0
		lineageTag: f9eb1d8b-74c2-4768-98b1-a4e280023dfb

	measure '% Students with Certificates' =
			
			DIVIDE(
			    DISTINCTCOUNT(FactCertificate[StudentKey]),
			    DISTINCTCOUNT(DimStudent[Student_ID])
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a7887ad1-393c-4605-92ac-10ebf4f033f5

	measure 'Total Instructors Rated' = DISTINCTCOUNT(FactStudentRating[InstructorKey])
		formatString: 0
		lineageTag: f03bb04a-c394-4ba6-ac73-957b67d66dfa

	measure 'Total Freelance Earning' = SUM(FactFreelanceJob[Job_Earn])
		formatString: 0.0
		lineageTag: cf03686d-3d26-4e12-beb7-51e454c1afd0

	measure '% Students with Freelance Jobs' =
			
			DIVIDE(
			    DISTINCTCOUNT(FactFreelanceJob[StudentKey]),
			    DISTINCTCOUNT(DimStudent[Student_ID])
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 6c66eff0-8430-422a-91d2-1f825b5093cd

	measure 'Total Freelance Jobs' = COUNTROWS(FactFreelanceJob)
		formatString: 0
		lineageTag: 37ddbe72-4f8e-4982-b2c4-8e600278079a

	measure 'Average Certificates per Student' = DIVIDE(COUNTROWS(FactCertificate), DISTINCTCOUNT(DimStudent[Student_ID]))
		lineageTag: b22c51ed-35dd-402c-825c-8ad96fed5798

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Certified Students' = DISTINCTCOUNT(FactCertificate[StudentKey])
		formatString: 0.0
		lineageTag: 1a864770-054d-4a60-9195-28e3db5d6659

	measure 'Average Earnings' = AVERAGE(FactFreelanceJob[Job_Earn])
		formatString: #,0
		lineageTag: 47d05000-3696-4d89-bee0-2af7b172188f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Distinct Both Certified and Freelance' =
			
			VAR Certs = VALUES(FactCertificate[StudentKey])
			VAR Fls = VALUES(FactFreelanceJob[StudentKey])
			RETURN
			COUNTROWS(INTERSECT(Certs, Fls))
		formatString: 0
		lineageTag: bfe02baf-01c1-4245-9b23-228234f23a11

	measure 'Avg Earnings (Freelancers Only)' =
			
			AVERAGEX(
			    FILTER(
			        VALUES(DimStudent[StudentKey]),
			        CALCULATE(COUNTROWS(FactFreelanceJob)) > 0
			    ),
			    CALCULATE([Total Freelance Earnings])
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 17d4b512-3880-4be7-b919-d702f967b8c3

	measure 'Avg Grade (Students with Freelance)' = ```
			
			CALCULATE(
			    [Avg. St. Grade],
			    FILTER(
			        VALUES(DimStudent[StudentKey]),
			        CALCULATE(COUNTROWS(FactFreelanceJob)) > 0
			    )
			)
			
			```
		lineageTag: 3cdc3e28-1628-45e9-865b-47e13046c487

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Earnings (Freelance + Certificate)' =
			
			AVERAGEX(
			    FILTER(
			        VALUES(DimStudent[StudentKey]),
			        CALCULATE(
			            COUNTROWS(FactFreelanceJob),
			            USERELATIONSHIP(DimStudent[StudentKey], FactFreelanceJob[StudentKey])
			        ) > 0 &&
			        CALCULATE(
			            COUNTROWS(FactCertificate),
			            USERELATIONSHIP(DimStudent[StudentKey], FactCertificate[StudentKey])
			        ) > 0
			    ),
			    CALCULATE(
			        [Total Freelance Earnings],
			        USERELATIONSHIP(DimStudent[StudentKey], FactFreelanceJob[StudentKey])
			    )
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 97528ce6-d618-4f7c-906d-e9dc0f861679

	measure 'Avg Salary (With Certs)' =
			
			CALCULATE(
			    [Avg. St. Salary],
			    FILTER(VALUES(DimStudent[StudentKey]),
			        CALCULATE(COUNTROWS(FactCertificate)) > 0)
			)
		lineageTag: eb01d257-b463-4c27-8463-7dc7ca3a7d8b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Salary (Without Certs)' =
			
			CALCULATE(
			    [Avg. St. Salary],
			    FILTER(VALUES(DimStudent[StudentKey]),
			        CALCULATE(COUNTROWS(FactCertificate)) = 0)
			)
		lineageTag: 59a17b1e-b2b3-4f11-83e4-4bf52d079ebd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Grade (With Certs)' =
			
			CALCULATE(
			    [Avg. St. Grade],
			    FILTER(VALUES(DimStudent[StudentKey]),
			        CALCULATE(COUNTROWS(FactCertificate)) > 0)
			)
		lineageTag: 834f00b7-223f-42e2-a92f-b4e017ebda03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Grade (Without Certs)' =
			
			CALCULATE(
			    [Avg. St. Grade],
			    FILTER(VALUES(DimStudent[StudentKey]),
			        CALCULATE(COUNTROWS(FactCertificate)) = 0)
			)
		lineageTag: c5c54c5f-7115-4eae-94f3-310abc319478

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Age' = AVERAGE(DimStudent[Age])
		lineageTag: 29638f44-61b5-4bd4-a2eb-72ec6eec104d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min Age' =
			
			MINX(
			    DimStudent,
			    DATEDIFF(DimStudent[Student_Birthdate], TODAY(), YEAR)
			)
		formatString: 0
		lineageTag: 3386591a-0f14-4982-98f3-2e3714d15e70

	measure 'Max Age' =
			
			MAXX(
			    DimStudent,
			    DATEDIFF(DimStudent[Student_Birthdate], TODAY(), YEAR)
			)
		formatString: 0
		lineageTag: e46aa084-8321-419a-8e65-4b093d9e495f

	column Column
		formatString: 0
		lineageTag: 0c4cdde3-d19b-46b0-9a0e-698d01c80b79
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition HaithamMeasures = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 9de82e9f7b134d34977d7634f4ec8893

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

