table HimaMeasures
	lineageTag: 6099bf17-07d4-458a-b783-1ce10be9c732

	measure 'Total failed' = [Total Students] - [Total Graduates]
		formatString: 0
		lineageTag: 4d17e099-d589-43a7-8bf2-e0591617619e

	measure 'Graduation %' = DIVIDE([Total Graduates] , [Total Students])
		formatString: 0%;-0%;0%
		lineageTag: 02f0d267-1c65-4bb9-92b8-ec91782e1eab

	measure 'Total student Salary' = SUM(FactStudentOutcomes[Salary])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 6364bc1c-e761-4a48-b161-34426d95ce67

	measure 'Avg Hired Graduates Salaries' = CALCULATE(AVERAGE(FactStudentOutcomes[Salary]), USERELATIONSHIP(FactStudentOutcomes[HireDateKey], DimDate[DateKey]))
		lineageTag: ab554e5c-d6db-426f-8203-c30ec9a268cf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Certicates cost' = CALCULATE(AVERAGE(FactCertificate[Certificate_Cost]))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: f5955ef2-9c14-4a2f-ae75-7e167a91e399

	measure 'Total Freelancers' = DISTINCTCOUNT(FactFreelanceJob[StudentKey])
		formatString: 0.0
		lineageTag: 4ca0055e-b5f4-4ffb-8cbf-bb4bcd225f4d

	measure 'Total Hired Graduates' = [Total Graduates] * [Employment Rate %]
		formatString: 0
		lineageTag: d8f5d496-e963-4b78-b1e7-c3e57b72d8de

	measure 'Total Companies' = COUNTROWS(DimCompany)
		formatString: 0
		lineageTag: ee375a55-aed8-42eb-8345-4a45e52bcdac

	measure 'Total Counties' = DISTINCTCOUNT(DimStudent[County])
		formatString: 0
		lineageTag: e2ab95af-db22-4dd6-8e15-abd93bacc364

	measure 'Total Certicates cost' = CALCULATE(sum(FactCertificate[Certificate_Cost]))
		lineageTag: cb3e609f-b302-4b64-8dfd-a2f0f165f56f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Employment Rate % per County' = CALCULATE(DIVIDE(COUNT(FactStudentOutcomes[StudentKey]), [Total Graduates]),DimStudent[County])
		lineageTag: 46cd60d1-22d5-41b7-a36f-05e6a125a23a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Branch Salary %' =
			
			DIVIDE(
			    [Total student Salary],
			    CALCULATE([Total student Salary], ALL(DimBranch))
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b155b2a9-c2f8-4fc9-8f56-2083ca11ef96

	measure 'Total Track Salary %' =
			
			DIVIDE(
			    [Total student Salary],
			    CALCULATE([Total student Salary], ALL(DimTrack))
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0a5b18d0-fa0f-48cf-869a-2d473980309f

	measure 'Avg Costs (Freelance + Certificate)' =
			
			AVERAGEX(
			    FILTER(
			        VALUES(DimStudent[StudentKey]),
			        CALCULATE(
			            COUNTROWS(FactFreelanceJob),
			            USERELATIONSHIP(DimStudent[StudentKey], FactFreelanceJob[StudentKey])
			        ) > 0 &&
			        CALCULATE(
			            COUNTROWS(FactCertificate),
			            USERELATIONSHIP(DimStudent[StudentKey], FactCertificate[StudentKey])
			        ) > 0
			    ),
			    CALCULATE(
			        [Total Certicates cost],
			        USERELATIONSHIP(DimStudent[StudentKey], FactFreelanceJob[StudentKey])
			    )
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 2e55ac19-b7ff-4f3e-b615-9e371e57aa2e

	measure 'Total Earnings (Freelance + Certificate)' =
			
			SUMX(
			    FILTER(
			        VALUES(DimStudent[StudentKey]),
			        CALCULATE(
			            COUNTROWS(FactFreelanceJob),
			            USERELATIONSHIP(DimStudent[StudentKey], FactFreelanceJob[StudentKey])
			        ) > 0 &&
			        CALCULATE(
			            COUNTROWS(FactCertificate),
			            USERELATIONSHIP(DimStudent[StudentKey], FactCertificate[StudentKey])
			        ) > 0
			    ),
			    CALCULATE(
			        [Total Freelance Earnings],
			        USERELATIONSHIP(DimStudent[StudentKey], FactFreelanceJob[StudentKey])
			    )
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 65e90833-ddad-4244-a555-21307c187fa2

	measure 'Total Costs (Freelance + Certificate)' =
			
			SUMX(
			    FILTER(
			        VALUES(DimStudent[StudentKey]),
			        CALCULATE(
			            COUNTROWS(FactFreelanceJob),
			            USERELATIONSHIP(DimStudent[StudentKey], FactFreelanceJob[StudentKey])
			        ) > 0 &&
			        CALCULATE(
			            COUNTROWS(FactCertificate),
			            USERELATIONSHIP(DimStudent[StudentKey], FactCertificate[StudentKey])
			        ) > 0
			    ),
			    CALCULATE(
			        [Total Certicates cost],
			        USERELATIONSHIP(DimStudent[StudentKey], FactFreelanceJob[StudentKey])
			    )
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: f16f57cd-1a87-4955-81b7-998c0829aa47

	column Column
		formatString: 0
		lineageTag: 6e458eb2-9f3f-44e3-a01b-49ce6d3b49de
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition HimaMeasures = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = a953d2e9a91a43c28d4666fe250f306e

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

