table HIma
	lineageTag: 40783245-a8c1-4701-9f1a-02aac783e174

	measure 'Average Student Salary' = AVERAGE(FactStudentOutcomes[Salary])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 0b247ed0-e54f-436e-90fa-b6500f9302f3

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Total Failed' = DISTINCTCOUNT(FactStudentFailure[StudentKey])
		formatString: 0
		lineageTag: ac37ca51-b270-4bff-9a9d-8174dfe366d6

	measure 'Graduation %' = 1 - DIVIDE([Total Failed],[Total students])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: db7889e2-1d8d-4f78-a816-3a633ef2e197

	measure 'Freelanced %' = DIVIDE( [Students Freelanced], [Total Graduated] )
		formatString: 0%;-0%;0%
		lineageTag: d5abeb2a-4413-4686-8c70-5790a0988567

	measure 'Total Graduated' = [Total students] - [Total Failed]
		formatString: 0
		lineageTag: b79fc266-ba2e-4e23-96ba-b99052dc2b1b

	measure 'Total Companies' = CALCULATE(DISTINCTCOUNT(DimCompany[Company_ID]),USERELATIONSHIP(DimCompany[CompanyKey],FactStudentOutcomes[CompanyKey]))
		formatString: 0
		lineageTag: cda30028-4cd4-46d9-8e21-2b0b3919dee3

	measure 'Total students' = DISTINCTCOUNT(DimStudent[Student_ID])
		formatString: 0
		lineageTag: 98f06c94-fcec-46a3-aaee-e168ec9ac209

	measure Students = DISTINCTCOUNT(FactStudentPerformance[StudentKey])
		formatString: 0
		lineageTag: f4a5f4e3-2705-4d72-ae35-881f55f3d34b

	measure 'Total No. Students Employed' = [Total Graduated] * [Freelanced %]
		lineageTag: c2e27858-cc78-4c9e-ab77-72b682280bfa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Earn' = SUM(FactFreelanceJob[Job_Earn])
		lineageTag: c4570890-8454-4277-9543-c1f564de8803

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Earn' = AVERAGE(FactFreelanceJob[Job_Earn])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 03453fbe-4fcc-411e-8080-566b4ddd5fad

	measure 'Students Freelanced' = CALCULATE(DISTINCTCOUNT(FactFreelanceJob[StudentKey]),USERELATIONSHIP(DimStudent[StudentKey],FactStudentOutcomes[StudentKey]))
		formatString: 0
		lineageTag: 09b244f9-a05b-4235-abe1-e717add83b2a

	measure 'Total JobSites' = DISTINCTCOUNT(DimJobSite[JobSiteKey])
		formatString: 0
		lineageTag: 9a449401-4f62-493e-9a2b-1535b8411545

	measure 'Avg Cert Cost' = AVERAGE(FactCertificate[Certificate_Cost])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 88d6ed5f-f0b3-4707-a004-e161666324bf

	column Column
		formatString: 0
		lineageTag: b19f10f1-3dd4-41c9-a6db-d761280b2096
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition HIma = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = b5f8731c19f848258ce220aeac393843

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

